sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - v6
  - v8
  - v10
  - stable
after_success:
  - npm run semantic-release
env:
  global:
      # GH_TOKEN
    - secure: TV3UxGd/tUaeyVBiuiB52cvfxIQAX+kz51g9CBCQA7tQjdJWsJnjrKL9/tsrUYfriN44PHlOPJm5JIIwkEYyWooyZFCZbkhok86+WCpvrnAjlneBm+VZBlsNTp7VOxL4gaiZL8QDKyLCz7xwIWNOv2ti1VlZlwHv8TRa5XkuX2ii+FWBhPpdWooGoXkDeWp0OQO81s8tnqwDJNlWmzvrpPK/T+vV8lyn6tJzIib9sKLPOtNmHfYhOfoxtxtP0krMGQLUqzNbwsdrdeVAtd30ejPqQTNyta8FLtFOXdLdNBPvMQ9LzQ5t8umK3bSijFN6jlS1YWkSUQWyQMMf8LlNAgSlElA1N0DiMedk/hqpvVxTPGspagQFo9UvmHvfaDOAkT4pjXB4hPA/vPVpKtBzTA81KebhYjm6a2V20uqp8/jaYLegRDqZEJ8OdzeWPkoIfoXkFbcasXM+m1qWmipkhnWjnx10Hf46jXrNzTB9cmkaRPcr86laMvM6bhcuBxqCxzM2LUY2hoS3De+YsbTc9c0vTyY0QG+lZzX3Q2p7dAWm//ItjiJSRJ9P8TWM3KmVEjBTxr7yqmtbv11MuGGxOp6uLilYJG8miJLcemQHcAxe/5+MiVc8ev+90dypdLaHVaClWUXI0SOTOHoKf5ggycvCXidOCxFzNqJJxUlFrks=
      # NPM_TOKEN 	7fc1
    - secure: JqPgVQiYdo8avWh72PVKDVKYOncgHJ8YHL2lSYiHCFWXk43SJhD+znbt63rZLQn7ePNKq6b9yL1ffuj+VkA4y79NGilLw9hQlZDMVI12+08+mm/PHCg79qEcu7Rg8lkbqsHtnjUDc3ssVefNMItjBxfiAWcoP4qke7wucBmaZT1fhzyl7CluwDrcgpCZG8VLCJ7YjQy59tzL/wWn8AfMIAQiWqhGDYf3BhAh2RKngQjblBJ5bn2hRq8KjELMbNz8/i6BIJV9v3xk4P9IHryQiFeJM0Unm0DxT9JNgKy9TWhyRmVpOPnPZTPQJBtZxmnGfxSVTAiS6SqrdZp2MUwG1W2I2rpgmKK6x4G+0SPOgRfRhjiSUh2w37HKELnSIhirmBRQlDHqbYKlTI75V57LMFcQSfUS4GubIqwlYkvsQuFX/ePQ6nFIp765PM4cz4ZnnzTohYcDJxpnrbEbnRBCCjKSXJmLQQ2D8n8erk/14pjWrnG9em9jvCm1oay9nOK+dPhYSHU8dB2jtBb+24YKBukaavTqsco3BczSZ62NHIPzwUzBhWaAwYfYE+P4n8m3G7s3vfBUmeG6Fxaqv92zOQfwk48rcr+V6JPbzY21yZ/BPIlGx29b8TO+0jMGZBZlu4dmsckYb6d1GB8b4fKN2ZFSyTuOZrb54B70ywlXh8Q=
